// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/submit": {
    params: {};
  };
  "/inventory": {
    params: {};
  };
  "/MonsterInfo": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/submit" | "/inventory" | "/MonsterInfo";
  };
  "routes/MainLayout.tsx": {
    id: "routes/MainLayout";
    page: "/" | "/submit" | "/inventory" | "/MonsterInfo";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/SubmitItem.tsx": {
    id: "routes/SubmitItem";
    page: "/submit";
  };
  "routes/Inventory.tsx": {
    id: "routes/Inventory";
    page: "/inventory";
  };
  "routes/MonsterInfo.tsx": {
    id: "routes/MonsterInfo";
    page: "/MonsterInfo";
  };
};